### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by dominikzogg** [peakphp/http#1]
I try to additional support for peakphp as a microframework on my skeleton https://github.com/chubbyphp/petstore/tree/peakphpusing based on peakphp/http.

I works so far, but i had to drop some functionality and replace the route class.

What do you think about the following?
- Add Route Args as Attributes: https://github.com/chubbyphp/petstore/blob/peakphp/app/Peak/Route.php#L107-L112
- Add a route generator
- Adapt stack to resolve any string from ResourceResolver (container)

**Comment by 1franck** [comment]
Hi,

Thanks for the feedback!

> Add Route Args as Attributes: https://github.com/chubbyphp/petstore/blob/peakphp/app/Peak/Route.php#L107-L112

This is a good idea. I'm releasing v4.1.2 which will include this change.

> Add a route generator

Can you explain me more why ?

Update: i saw your file https://github.com/chubbyphp/petstore/blob/peakphp/app/web.php and now i understand why a route generator could be handy ;)

> Adapt stack to resolve any string from ResourceResolver 

Actually, Peak\Http\Request\HandlerResolver is able to resolve namespace as string with the container. The Stack doesn't directly resolve handlers, but pass it to the HandlerResolver which will return a valid handler instance or throw an exception.

**Comment by dominikzogg** [comment]
Hello @1Franck 

Your welcome.

What i mean is the possibly to name routes and have some code like:

`$service->generate('entity_read', ['id' => 1])`which leads to: `/api/entity/1`

About the HandlerResolver:

I my case it's not a namespace only a service name (namespace to a generic controller concatenated with a namespace of a entity).

https://github.com/chubbyphp/petstore/blob/peakphp/app/web.php#L69

So its more: its a string and not a callable by itself, get it from $container

**Comment by 1franck** [comment]
for the HandlerResolver, you could extends it and overload method resolveString() to implements this behavior

**Comment by dominikzogg** [comment]
@1Franck works

**Comment by 1franck** [comment]
Great!

in file https://github.com/chubbyphp/petstore/blob/peakphp/app/web.php, i saw you instantiate components manually (Route, Stack, etc..)

you could use Peak Application (https://packagist.org/packages/peak/bedrock) to simplify the process.

quick example:

```php
$app = new Application(
    new Kernel($env, $container),
    new HandlerResolver($container)
);

$app
    ->stack(CorsMiddleware::class)
    ->get('/', IndexRequestHandler::class)
    ->group('/api', function() use ($app) {
        $app
            ->get('/', SwaggerIndexRequestHandler::class)
            ->get('/swagger', SwaggerYamlRequestHandler::class)
            ->get('/ping', [
                AcceptAndContentTypeMiddleware::class,
                PingRequestHandler::class,
            ]);
        // ... 
    });


return $app;


// and in public/index.php, you could just do something like this:

/** @var Peak\Bedrock\Http\Application $app */
$app = (require __DIR__ . '/../app/web.php')(getenv('APP_ENV'));
$app->run((new ServerRequestFactory())->createFromGlobals(), new Emitter());
```

**Comment by dominikzogg** [comment]
@1Franck good point thanks , but i dislike its (hard) dependency to command line:

https://github.com/peakphp/framework/blob/master/src/Bedrock/composer.json#L21-L22

**Comment by 1franck** [comment]
@dominikzogg i moved them to suggest section of composer since it's only used by `Peak\Bedrock\Cli\Application`

https://github.com/peakphp/framework/blob/master/src/Bedrock/composer.json#L23-L24

I'm releasing 4.2.0 with this fix so you can give it a try if you want.

Thanks again for the feedback, really appreciated :)

**Comment by dominikzogg** [comment]
Cool Thanks

Is there any use of symfony/process? in the CLI code anyway? Am i to
stupied to find it?

Am Do., 9. Jan. 2020 um 16:10 Uhr schrieb François Lajoie <
notifications@github.com>:

**Comment by 1franck** [comment]
@dominikzogg symfony/process can be useful for calling system commands (it replace exec, passthru, shell_exec).

**Comment by dominikzogg** [comment]
@1Franck get that, but i mean i can't find that it's already used in the code base already

**Comment by dominikzogg** [comment]
@1Franck adapted the code as suggested (use the Application)

**Comment by 1franck** [comment]
@dominikzogg oh i understand now. No it is not used anywhere in Peak directly. I just find it useful when writing console command and have the habit to include it with symfony/console.

**Comment by dominikzogg** [comment]
@1Franck any plan to add something like that (/path generator)?

> `$service->generate('entity_read', ['id' => 1])`which leads to: `/api/entity/1`

**Comment by 1franck** [comment]
@dominikzogg i have no plan for this right now, but if you have the time to come up with something, i will be happy to look at your pull request.
